In [1]:
import torch

In [2]:
t = torch.Tensor(2,3,4)
type(t)

torch.Tensor

In [11]:
sz_str = "\u00D7".join(map(str, t.size()))
print(f"t size: {sz_str}")

t size: 2×3×4


In [12]:
t.numel()

24

In [14]:
t.ndim

3

In [16]:
t.dim()

3

In [17]:
t.random_(10)

tensor([[[9., 9., 1., 2.],
         [0., 1., 4., 0.],
         [5., 7., 3., 1.]],

        [[6., 5., 0., 2.],
         [7., 9., 0., 1.],
         [2., 3., 5., 9.]]])

In [21]:
r = torch.Tensor(t) # copy construction
r.resize_(3,8)

tensor([[9., 9., 1., 2., 0., 1., 4., 0.],
        [5., 7., 3., 1., 6., 5., 0., 2.],
        [7., 9., 0., 1., 2., 3., 5., 9.]])

In [28]:
s = r.clone()

In [29]:
s is r

False

In [41]:
v = torch.Tensor([ 1, 2, 3, 4 ])
v

tensor([1., 2., 3., 4.])

In [42]:
torch.*Tensor?

torch.BFloat16Tensor
torch.BoolTensor
torch.ByteTensor
torch.CharTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.IntTensor
torch.LongTensor
torch.ShortTensor
torch.Tensor